[package]
name = "rust_kiss3d"
version = "0.1.0"
authors = ["gabriel <gabrielgoller123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.27.0"
nalgebra = "0.23.0"
